import "dotenv/config";
import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read plugin metadata
const manifest = JSON.parse(
  fs.readFileSync(path.join(__dirname, "manifest.json"), "utf-8")
);

const prod = process.argv[2] === "production";

// --- Auto-copy configuration ---
// Set DEV_PLUGIN_PATH to the plugin directory inside your vault.
// Example: ~/obsidian/MyVault/.obsidian/plugins/my-plugin
//
// You can set this in your shell profile, a .env file, or inline:
//   DEV_PLUGIN_PATH="$HOME/obsidian/MyVault/.obsidian/plugins/my-plugin" npm run dev
const PLUGIN_ID = manifest.id;
if (!prod && !process.env.DEV_PLUGIN_PATH) {
  console.error(
    `DEV_PLUGIN_PATH is not set. Set it to the plugin directory inside your vault.\n` +
    `Example: DEV_PLUGIN_PATH="$HOME/obsidian/MyVault/.obsidian/plugins/${PLUGIN_ID}" npm run dev`
  );
  process.exit(1);
}
const DEV_PLUGIN_PATH = process.env.DEV_PLUGIN_PATH || "";

// --- Copy plugin ---
const outputDir = path.join(__dirname, "output");

const copyPlugin = {
  name: "copy-build-artifacts",
  setup(build) {
    build.onEnd(() => {
      try {
        if (prod) {
          // Production: copy manifest and styles into output/ for the release workflow
          fs.copyFileSync(
            path.join(__dirname, "manifest.json"),
            path.join(outputDir, "manifest.json")
          );
          fs.copyFileSync(
            path.join(__dirname, "styles.css"),
            path.join(outputDir, "styles.css")
          );
          console.log("✓ Copied manifest.json and styles.css → output/");
        } else {
          // Dev: copy to vault plugin directory
          const targetMain = path.join(DEV_PLUGIN_PATH, "main.js");
          const manifestTarget = path.join(DEV_PLUGIN_PATH, "manifest.json");

          if (!fs.existsSync(DEV_PLUGIN_PATH)) {
            console.error(`Target directory does not exist: ${DEV_PLUGIN_PATH}`);
            console.error(
              `Create it first: mkdir -p "${DEV_PLUGIN_PATH}"`
            );
            return;
          }

          fs.copyFileSync(path.join(outputDir, "main.js"), targetMain);
          console.log(`✓ Copied main.js → ${targetMain}`);

          const devManifest = { ...manifest, version: "1.0.0" };
          fs.writeFileSync(
            manifestTarget,
            JSON.stringify(devManifest, null, 2) + "\n"
          );
          console.log(`✓ Wrote dev manifest → ${manifestTarget}`);
        }
      } catch (err) {
        console.error(`Copy failed: ${err.message}`);
      }
    });
  },
};

// --- esbuild config ---
const context = await esbuild.context({
  banner: { js: "/* generated by esbuild - see source repo */" },
  entryPoints: ["main.ts"],
  bundle: true,
  define: {
    PLUGIN_VERSION: JSON.stringify(manifest.version),
  },
  external: [
    "obsidian",
    "electron",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  treeShaking: true,
  outfile: "output/main.js",
  sourcemap: prod ? false : "inline",
  minify: prod,
  plugins: [copyPlugin],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.rebuild();
  await context.watch();
}
